Search ts21 26 error messages for post request
digital-futures-academy/crm-api pull request #17
Opened 2021-06-02 18:27 UTC by joshjames279

Added JSON error messages to the controller for searches that don't exist and for use of non alphabetical symbols.

2021-06-02 18:40 UTC, dearshrewdwit requested changes
Nice stuff!

See inline comments

2021-06-02 18:40 UTC, dearshrewdwit commented on build.gradle
> +	implementation 			'org.json:json:20171018'
Can you document why this is needed?

2021-06-02 18:40 UTC, dearshrewdwit commented on src/main/resources/data-postgres.sql
> +INSERT INTO users(id, first_name, last_name, email, photo, education) VALUES(1, 'Ada', 'Lovelace', 'ada@lovelace.com', 'img', 'education');
Can you remove this file - this should no longer be part of the app initialisation process

2021-06-02 19:33 UTC, joshjames279 commented on src/main/resources/data-postgres.sql
> +INSERT INTO users(id, first_name, last_name, email, photo, education) VALUES(1, 'Ada', 'Lovelace', 'ada@lovelace.com', 'img', 'education');
Done

2021-06-02 19:47 UTC, joshjames279 commented on build.gradle
> +	implementation 			'org.json:json:20171018'
Edited the comment for the pull request

2021-06-02 20:20 UTC, joshjames279 commented on build.gradle
> +	implementation 			'org.json:json:20171018'
Done

2021-06-02 20:39 UTC, AntMousinho approved these changes

2021-06-03 08:42 UTC, dearshrewdwit approved these changes

2021-06-03 08:44 UTC, merged